steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/strategic-block-455218-i3/flask-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/strategic-block-455218-i3/flask-app']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
  - 'gcr.io/strategic-block-455218-i3/flask-app'

